---
- hosts: localhost
  become: true
  vars:
    compose_file: "docker-compose.yml"

  tasks:
  - name: Start Init
    command: docker-compose -f "{{ compose_file }}" up -d

#  - name: Stop Init
#    command: docker-compose -f "{{ compose_file }}" down

