version: "3"

networks:
 private_network:
  ipam:
   driver: default
   config:
    - subnet: 10.2.0.0/24

services:
 unbound:
  image: "mvance/unbound:latest"
  container_name: unbound
  restart: unless-stopped
  hostname: "unbound"
  volumes:
   - "./unbound:/opt/unbound/etc/unbound/"
  networks:
   private_network:
    ipv4_address: 10.2.0.200

 adguard:
  depends_on: [unbound]
  container_name: adguard
  image: adguard/adguardhome
  restart: unless-stopped
  hostname: adguard
  # Volumes store your data between container upgrades
  volumes:
   - "./adguard/opt-adguard-work:/opt/adguardhome/work"
   - "./adguard/opt-adguard-conf:/opt/adguardhome/conf"
  networks:
   private_network:
    ipv4_address: 10.2.0.100