version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  unbound:
    image: custom-unbound
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/"
    networks:
      private_network:
        ipv4_address: 10.2.0.200
    ports:
      - "2222:22"  # Port SSH
  adguard:
    depends_on: [unbound]
    container_name: adguard
    image: custom-adguard
    restart: unless-stopped
    hostname: "adguard"
    volumes:
      - "./adguard/opt-adguard-work:/opt/adguardhome/work"
      - "./adguard/opt-adguard-conf:/opt/adguardhome/conf"
    networks:
      private_network:
        ipv4_address: 10.2.0.100
    ports:
      - "2223:22"  # Ajout du mappage du port SSH
